<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>PathfinderDb.Schema</RootNamespace>
    <AssemblyName>PathfinderDb.Schema</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>

    <PackageId>PathfinderDb.Schema</PackageId>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>Pathfinder-fr.org</Authors>
    <Description>PathfinderDb project schema library.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/pathfinder-fr/PathfinderDb.Schema</RepositoryUrl>
    <PackageTags>pathfinder;schema;xml;serialization</PackageTags>
  </PropertyGroup>
</Project>
