<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>PathfinderDb.Schema</RootNamespace>
    <AssemblyName>PathfinderDb.Schema</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>

    <PackageId>PathfinderDb.Schema</PackageId>
    <VersionPrefix>2.0.1</VersionPrefix>
    <Authors>Pathfinder-fr.org</Authors>
    <Description>PathfinderDb project schema library.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/pathfinder-fr/PathfinderDb.Schema</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>pathfinder;schema;xml;serialization</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>package-icon.png</PackageIcon>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md"
          Pack="true"
          PackagePath="README.md"
          Link="README.md" />
    <None Include="..\..\LICENSE.txt"
          Pack="true"
          PackagePath="LICENSE.txt"
          Link="LICENSE.txt" />
    <None Include="..\..\CHANGELOG.md"
          Pack="true"
          PackagePath="CHANGELOG.md"
          Link="CHANGELOG.md" />
    <None Include="..\..\package-icon.png"
          Pack="true"
          PackagePath="package-icon.png"
          Link="package-icon.png" />
    <None Include="..\..\xml\**\*.xsd"
          Pack="true"
          PackagePath="docs\xsd\%(RecursiveDir)%(Filename)%(Extension)"
          Link="docs\xsd\%(RecursiveDir)%(Filename)%(Extension)" />
    <None Include="..\..\xml\samples\**\*.xml"
          Pack="true"
          PackagePath="docs\samples\%(RecursiveDir)%(Filename)%(Extension)"
          Link="docs\samples\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
